server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: b6e0185c2e20fe
    password: 92e1a01b364b6a

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

